' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml class_diagram_modifiers

package modifier_case {
    abstract class BaseJob {
        func() = 0
    }

    class ServiceImpl {
        {abstract} + Run() : ResultBlank
        {static} + Finalize()
    }

    class AllowModeChangeService {
        using AllowOpModeChangeOutput = std::uint8_t;
        + Func(const AllowOpModeChangeOutput input_1, std::shared_ptr<std::uint32_t> json_parser = nullptr) noexcept : static std::Result<Uptr>
    }
}

@enduml
