# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "puml_serializer",
    srcs = ["src/lib.rs"],
    visibility = ["//plantuml/parser:__subpackages__"],
    deps = [
        ":class_serializer",
        ":component_serializer",
        ":sequence_serializer",
    ],
)

alias(
    name = "component_serializer",
    actual = "//plantuml/parser/puml_serializer/src/serialize:puml_serialize_component",
    visibility = ["//plantuml/parser:__subpackages__"],
)

alias(
    name = "class_serializer",
    actual = "//plantuml/parser/puml_serializer/src/serialize:puml_serialize_class",
    visibility = ["//plantuml/parser:__subpackages__"],
)

alias(
    name = "sequence_serializer",
    actual = "//plantuml/parser/puml_serializer/src/serialize:puml_serialize_sequence",
    visibility = ["//plantuml/parser:__subpackages__"],
)
